### ISSUE TITLE
What version or git hash of World did you use?

### ISSUE THREAD

**Issue by kai5263499** [but80/voispire#1]
`go build` gives me the following which makes me think I'm using a different world library than you are 

```
# github.com/but80/voispire/internal/world
internal/world/dio.go:82:19: cannot use toFFTComplexPtr(y_spectrum) (type *_Ctype_fft_complex) as type *[2]_Ctype_double in argument to _Cfunc_CallGetF0CandidateFromRawEvent
internal/world/dio.go:307:34: copts.fft_size undefined (type *_Ctype_struct___0 has no field or method fft_size)
```

What was the commit hash of the world library you were building against?

**Comment by but80** [comment]
Sorry for not replying for a long time.
There was no problem in my environment (macOS) at that time, but now when I built with WSL, it was reproduced.
`*_Ctype_fft_complex` and `*[2]_Ctype_double` are substantially the same type in C, so the problem was solved by type casting.

https://github.com/but80/voispire/commit/1d8f1dbb5b81b5d7b0c836a32034525fd35d07d4#diff-fb1b82b523f178f3feec4b2eaff035ddR82

Since World is imported as a submodule with a particular revision, inconsistencies should not occur.
So it seems to be caused by the difference in environment.
